
-- ### REFERRAL SYSTEM SETUP ###

-- 1. Add new columns to the `profiles` table for referral functionality
ALTER TABLE public.profiles
ADD COLUMN referral_balance numeric DEFAULT 0,
ADD COLUMN payout_upi_id text,
ADD COLUMN payout_qr_code_url text;

-- 2. Create the `referrals` table to track successful referrals
CREATE TABLE public.referrals (
    id bigint generated by default as identity primary key,
    referrer_id uuid references public.profiles(id) not null,
    referred_id uuid references public.profiles(id) not null,
    commission_amount numeric not null,
    created_at timestamp with time zone default now() not null
);

-- 3. Create the `payout_requests` table to manage withdrawal requests
CREATE TABLE public.payout_requests (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(id) not null,
    amount numeric not null,
    status text default 'pending'::text not null, -- 'pending', 'completed', 'rejected'
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null,
    admin_notes text -- Optional notes from the admin
);


-- 4. Enable RLS for the new tables
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payout_requests ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS policies for `referrals`
CREATE POLICY "Users can view their own referrals"
ON public.referrals
FOR SELECT USING (auth.uid() = referrer_id);

-- 6. Create RLS policies for `payout_requests`
CREATE POLICY "Users can view their own payout requests"
ON public.payout_requests
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own payout requests"
ON public.payout_requests
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 7. Grant access to admin role for the new tables
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.referrals TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.payout_requests TO service_role;
