
'use server';

import { createClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';

export async function signup(formData: FormData) {
  const email = formData.get('email') as string;
  const password = formData.get('password') as string;
  const fullName = formData.get('full_name') as string;
  const planPurchased = formData.get('plan_purchased') as string;
  const transactionId = formData.get('transaction_id') as string;
  const referralCode = formData.get('referral_code') as string | null;
  
  const planPrice = parseFloat(formData.get('plan_price') as string);
  const couponCode = formData.get('coupon_code') as string;
  const discountAmount = parseFloat(formData.get('discount_amount') as string);
  const finalAmountPaid = parseFloat(formData.get('final_amount_paid') as string);

  const supabase = createClient();

  // Find the referrer user ID if a referral code was provided
  let referrerId: string | null = null;
  if (referralCode) {
    const { data: referrerProfile } = await supabase
      .from('profiles')
      .select('id')
      .eq('referral_code', referralCode.trim().toUpperCase())
      .single();
    
    if (referrerProfile) {
      referrerId = referrerProfile.id;
    } else {
        // If the code is invalid, we'll proceed without a referrer but won't block the signup.
        // The UI will handle showing the error to the user.
    }
  }


  const { data: { user }, error } = await supabase.auth.signUp({
    email,
    password,
    options: {
      data: {
        full_name: fullName,
        role: 'user',
        // The referral code is generated by a database trigger on new user creation
      },
    },
  });

  if (error) {
    return { error: error.message };
  }

  if (user) {
    const profileData: any = { 
        plan_purchased: planPurchased,
        transaction_id: transactionId,
        is_approved: false, // Explicitly set to not approved
        plan_price: planPrice,
        coupon_code: couponCode,
        discount_amount: discountAmount,
        final_amount_paid: finalAmountPaid,
    };
    
    if (referrerId) {
        profileData.referred_by = referrerId;
    }

    const { error: profileError } = await supabase
      .from('profiles')
      .update(profileData)
      .eq('id', user.id);

    if (profileError) {
      console.error('Failed to update profile:', profileError.message);
      // The error is likely here. Let's provide a more specific message.
      if (profileError.message.includes("column") && profileError.message.includes("does not exist")) {
         return { error: `Database schema is out of date. Please ask the assistant to update the database table.` };
      }
      return { error: `Could not save registration details: ${profileError.message}` };
    }
  }

  revalidatePath('/welcome');
  return { error: null, success: true };
}


export async function validateCoupon(code: string) {
  if (!code) {
    return { error: 'Coupon code cannot be empty.' };
  }
  const supabase = createClient();
  const { data, error } = await supabase
    .from('coupons')
    .select('discount_value')
    .eq('code', code.toUpperCase())
    .single();

  if (error || !data) {
    return { error: 'Invalid or expired coupon code.' };
  }

  return { discount: data.discount_value };
}

export async function validateReferralCode(code: string) {
  if (!code) {
    return { error: 'Referral code cannot be empty.' };
  }
  const supabase = createClient();
  const { data, error } = await supabase
    .from('profiles')
    .select('id')
    .eq('referral_code', code.trim().toUpperCase())
    .single();

  if (error || !data) {
    return { error: 'Invalid referral code.' };
  }

  return { success: true };
}

