
-- Add new columns to the profiles table for referral system
ALTER TABLE public.profiles
ADD COLUMN referral_balance numeric NOT NULL DEFAULT 0,
ADD COLUMN payout_upi_id text NULL,
ADD COLUMN payout_qr_code_url text NULL;

-- Create the referrals table to track successful referrals
CREATE TABLE public.referrals (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    referrer_id uuid NOT NULL,
    referred_id uuid NOT NULL,
    commission_amount numeric NOT NULL,
    is_commission_paid boolean NOT NULL DEFAULT false
);

ALTER TABLE public.referrals
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.referrals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.referrals
ADD CONSTRAINT referrals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.referrals
ADD CONSTRAINT referrals_referred_id_fkey FOREIGN KEY (referred_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.referrals
ADD CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

-- Create the payout_requests table
CREATE TABLE public.payout_requests (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    amount numeric NOT NULL,
    status text NOT NULL DEFAULT 'pending'::text, -- pending, completed, rejected
    payout_details jsonb NULL,
    processed_at timestamp with time zone NULL
);

ALTER TABLE public.payout_requests
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payout_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.payout_requests
ADD CONSTRAINT payout_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payout_requests
ADD CONSTRAINT payout_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

-- Add RLS policies for new tables
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payout_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own referrals"
ON public.referrals
FOR SELECT
USING (auth.uid() = referrer_id);

CREATE POLICY "Users can view their own payout requests"
ON public.payout_requests
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own payout requests"
ON public.payout_requests
FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can manage all referrals"
ON public.referrals
FOR ALL
USING (public.is_admin(auth.uid()));

CREATE POLICY "Admins can manage all payout requests"
ON public.payout_requests
FOR ALL
USING (public.is_admin(auth.uid()));
